spring:
  application:
    name: test

  cloud:
    sentinel:
      transport:
        dashboard: localhost:8999 # Sentinel 控制台地址，根据实际情况调整
        port: 8719

      eager: true # 立即加载规则，默认为false,防止启动后不生效
    #      datasource:
#        ds1:
#          file: # 使用 file 数据源
#            file: classpath:sentinel-rules.json # 规则文件路径
#            rule-type: degrade # 指定规则类型为降级规则
#          nacos: #可以配置到nacos，这里只演示
#            server-addr: localhost:8848 # Nacos 地址，根据实际情况调整
#            dataId: ${spring.application.name}-sentinel-rules
#            groupId: DEFAULT_GROUP
#            rule-type: flow # 支持 flow, degrade, param-flow, authority, system


    # Feign 配置
    feign:
      sentinel:
        enabled: true # 启用 Feign 的 Sentinel 集成

  # RabbitMQ 配置
  rabbitmq:
    host: 122.51.168.11
    port: 5672
    username: admin
    password: your_password
    virtual-host: /
    publisher-confirm-type: correlated  #开启发布确认
    publisher-returns: true            #开启发布者退回

  datasource:
    url: jdbc:mariadb://122.51.168.11:3306/new
    username: new
    password: m7bZGMRPtjYtwXda
    driver-class-name: org.mariadb.jdbc.Driver
    hikari:
      maximum-pool-size: 10              # 最大连接池大小
      minimum-idle: 5                    # 最小空闲连接数
      idle-timeout: 600000               # 空闲连接最大等待时间（毫秒）
      connection-timeout: 30000          # 连接超时时间（毫秒）
      max-lifetime: 1800000              # 连接最大生命周期（毫秒）
      pool-name: HikariCP                # 连接池名称
      validation-timeout: 3000          # 校验连接是否有效的超时时间（毫秒）
      leak-detection-threshold: 15000   # 连接泄漏检测时间（毫秒）
  jpa:
    hibernate:
      ddl-auto: update  # 可选的值：none, update, create, create-drop
    show-sql: true  # 显示 SQL 查询
    properties:
      hibernate:
        format_sql: true  # 格式化 SQL
        jdbc.time_zone: UTC
  sql:
    init:
      platform: mysql

#  rocketmq:
#    name-server: 122.51.168.11:9876  # RocketMQ NameServer 地址
#    producer:
#      group: your-producer-group
#    consumer:
#      group: your-consumer-group
#      enable-message-model: CLUSTERING  # 消息模型，支持 CLUSTERING 或 BROADCASTING

  data:
    redis:
      host: 122.51.168.11
      port: 6379
      password: ereq454df4yd4
      timeout: 2000ms
      jedis:
        pool:
          max-idle: 10         # Jedis 连接池配置，最大空闲连接数
          min-idle: 2         # Jedis 连接池配置，最小空闲连接数
          max-active: 15       # Jedis 连接池配置，最大连接数
          max-wait: 3000      # Jedis 连接池配置，最大等待时间，单位毫秒


mybatis-plus:
  global-config:
    db-config:
      id-type: auto  # 自动增长 ID 策略
      field-strategy: not_empty  # 字段策略：不为空时进行更新
  configuration:
    map-underscore-to-camel-case: true  # 将数据库字段下划线命名规则自动映射为 Java 驼峰命名

# 自定义配置
alipay:
  appId: your_alipay_app_id
  privateKey: your_alipay_private_key
  publicKey: your_alipay_public_key
  gatewayUrl: https://openapi.alipay.com/gateway.do # 或沙箱环境
  retry:
    queue: payment.retry.queue
    exchange: payment.retry.exchange
    routingKey: payment.retry.key
  delay:
    exchange: payment.delay.exchange # 延时交换机
    queue: payment.delay.queue

langchain4j:
  open-ai:
    chat-model:
      log-requests: true
      log-response: true
      # 课程测试 KEY，需要更换为实际可用 KEY
      api-key: sk-c07a71819a2947f2b2e5ec5e5e76438f
      model-name: qwen-turbo
      # 百炼兼容OpenAI接口规范，base_url为https://dashscope.aliyuncs.com/compatible-mode/v1
      base-url: https://dashscope.aliyuncs.com/compatible-mode/v1